AWS_ACCESS_KEY_ID="AKIASxxxxxYWIPKSOZ7NVWAHY"
AWS_SECRET_KEY='Li9t90phlMV7SxxxxxxxxxxKTR1PsbIRzwZfjgK/aTPMMccmxi'
AWS_ACCOUNT_ID="19047273xxxxx7949"
AWS_REGION="us-east-1"
AWS_RESOURCE_PREFIX="benchsci"
